{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "MyWorkOrderHeaders",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
         "ReadLink": "#Property:OrderHeaderReadLink"
    },
    "Properties": {
        "Phase": "X – Shutdown"
    },
    "Headers": {
        "OfflineOData.TransactionID": "#Property:OrderId"
    },
  
    "OnSuccess": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntitySuccessMessage.action",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntityFailureMessage.action",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "

}
