{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "MyWorkOrderHeaders",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "ZSystemCondition": "X – Shutdown"
    },
    "Headers": {
        "OfflineOData.TransactionID": "#Property:OrderId"
    },
  
    "OnSuccess": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntitySuccessMessage.action",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntityFailureMessage.action",
    "ValidationRule": "/SAPAssetManager/Rules/WorkOrders/CreateUpdate/WorkOrderCreateUpdateValidation.js",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "

}
